# Generated by Django 3.2.8 on 2021-11-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('problem_href', models.TextField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='unknown', max_length=50, null=True)),
                ('course_type', models.CharField(default='Others', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTypeTag',
            fields=[
                ('course_type_tag', models.CharField(default='study', max_length=24, primary_key=True, serialize=False)),
            ],
        ),
    ]
