# Generated by Django 3.2.8 on 2021-11-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('problem_id', models.IntegerField(default=1)),
            ],
        ),
    ]
