# Generated by Django 3.2.8 on 2021-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
