# Generated by Django 3.2.8 on 2021-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0004_auto_20211116_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output',
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.IntegerField(default=1),
        ),
    ]
