# Generated by Django 3.2.8 on 2021-11-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0006_auto_20211117_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='answer_authority',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='score',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='website_name',
        ),
    ]
