# Generated by Django 3.2.8 on 2021-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0007_auto_20211117_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(default=64),
        ),
    ]
