# Generated by Django 3.2.8 on 2021-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_auto_20211115_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataofstudentinclass',
            name='studentEmail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dataofteacherinclass',
            name='teacherEmail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
