# Generated by Django 3.2.8 on 2021-11-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0005_classhomework_homework_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataofstudentinclass',
            name='studentEmail',
        ),
        migrations.RemoveField(
            model_name='dataofteacherinclass',
            name='teacherEmail',
        ),
    ]
