# Generated by Django 3.2.8 on 2021-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(default='这个人没有写下简介。', max_length=10000, null=True),
        ),
    ]
